name: web_promo_2025
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animate_do: ^4.2.0
  flutter_gradient_animation_text: ^1.0.2
  photo_view: ^0.14.0
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/secciona/
    - assets/images/seccionb/
    - assets/images/seccionc/
    - assets/images/secciond/
    - assets/images/seccione/
    - assets/images/galeria/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
        - asset: assets/fonts/gilroy/Gilroy-Bold.otf
